# SPDX-FileCopyrightText: 2023-present pfSDK contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

# -- Name of the rom we are building.
ROM_TARGET = helloworld.pfxrom

# -- Finally the common makefile should be included last.
include $(PF_SDK_ROOT)/src/common.mk
