# SPDX-FileCopyrightText: 2023-present pfSDK contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

# -- Name of the objects we are building.
OBJECTS_TARGET = crt0.o

# -- Where we are installing the library.
INSTALL_DIR = ../../lib

# -- Finally the common makefile should be included last.
include $(PF_SDK_ROOT)/src/common.mk
